package org.example.Enums;

public enum RequestType {
    LOGIN,
    REGISTER,
    GET_ALL_PRODUCTS,
    ADD_PRODUCT,
    GET_PRODUCT,
    UPDATE_PRODUCT,
    DELETE_PRODUCT,
    CHECK_PRODUCT_EXISTS,
    SEARCH_PRODUCTS,
    GET_ALL_CUSTOMERS,
    GET_LAST_CUSTOMER_ID,
    ADD_CUSTOMER,
    UPDATE_CUSTOMER,
    DELETE_CUSTOMER,
    SEARCH_CUSTOMERS_ID,
    SEARCH_CUSTOMERS_SURNAME,
    GET_CUSTOMER,
    ADD_PURCHASE,
    SEARCH_PURCHASE_BY_CUSTOMER_ID,
    SEARCH_PURCHASE_BY_EMPLOYEE_ID,
    GET_ALL_EMPLOYEES,
    UPDATE_EMPLOYEE,
    GET_ALL_PURCHASES,
    GET_LOW_STOCK_ITEMS
}